# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: dsp-provisioning-api
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
    - arm64
archives:
- name_template: >-
    {{ .ProjectName }}_
    {{ .Version }}_
    {{- title .Os }}_
    {{ .Arch }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  disable: true
