name: changelog

permissions:
  id-token: write
  contents: write
  actions: write    

on:
  push:
    branches:
      - main

env:
  AUTORELEASE_DEFAULT_LABEL: "autorelease: pending"

jobs:
  release-please-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple

      - name: Get Name of release from commit name
        id: get_release_name
        run: |
          commit_message="${{ github.event.head_commit.message }}"
          version_tag="v$(echo "$commit_message" | cut -d' ' -f3)"
          echo "version_tag=$version_tag" >> "$GITHUB_OUTPUT"
        if: "${{ startsWith(github.event.head_commit.message, 'chore(master): release') }}"
      
    outputs:
      version_tag: ${{ steps.get_release_name.outputs.version_tag }}
  
  release:
    permissions:
      id-token: write
      contents: write
      actions: write    
    needs: release-please-action
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      version_tag: ${{ needs.release-please-action.outputs.version_tag }}
    if: "${{ startsWith(github.event.head_commit.message, 'chore(master): release') }}"
