name: changelog

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main

env:
  AUTORELEASE_DEFAULT_LABEL: "autorelease: pending"
  AUTORELEASE_TAGGED_LABEL: "autorelease: tagged"

jobs:
  release-please-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Remove Label autorelease pending
        run: |
          gh pr list -s merged -l ${{ env.AUTORELEASE_DEFAULT_LABEL }} --json number jq -r '.[].number' | xargs -n1 -I {} gh pr edit {} --remove-label ${{ env.AUTORELEASE_DEFAULT_LABEL }}

      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Release
    needs: release-please-action
    uses: ./.github/workflows/release.yml
    if: "${{ startsWith(github.event.head_commit.message, 'chore(main): release') }}"
