name: changelog

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  release-please-action:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print branch name
        run: echo "Branch name is ${{ github.head_ref }}"

      - name: NiqueToi
        if: github.head_ref == 'release-please--branches--main'
        uses: ./.github/workflows/release.yml
