name: changelog

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  release-please-action:
    runs-on: ubuntu-latest
    steps:
      - name: Print branch name
        run: |
          echo "ref: ${{ github.ref }}"
          echo "head_ref: ${{ github.head_ref }}"
          echo "base_ref: ${{ github.base_ref }}"
          echo "ref_name: ${{ github.ref_name }}"
          echo "event_name: ${{ github.event_name }}"
          echo "commit name: ${{ github.event.head_commit.message }}"
          
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: NiqueToi
        if: github.head_ref == 'release-please--branches--main'
        uses: ./.github/workflows/release.yml
