name: Release and Docker build and push to production JFrog

on:
  workflow_call:
    inputs:
      version_tag:
        description: "release tag"
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  input_validation:
    name: input validation
    runs-on: [self-hosted, Linux, standard]
    steps:
      - name: Validate input
        run: |
          if [ -z "${{ inputs.version_tag }}" ]; then
            echo "Missing version_tag input"
            exit 1
          fi

  release:
    name: release version
    runs-on: [ubuntu-latest]
    needs: input_validation

    steps:
      - name: test
        run: echo ${{ inputs.version_tag }}

  docker-build-push:
    timeout-minutes: 60
    name: Docker Build and Push
    runs-on: [ubuntu-latest]
    needs: input_validation

    steps:
    - name: test
      run: echo ${{ inputs.version_tag }}
