name: Release

on:
  workflow_call:
    inputs:
      version_tag:
        description: "release tag"
        required: true
        type: string

permissions:
  id-token: write
  contents: write
  actions: write

env:
  GO_VERSION: ^1.22

jobs:
  input_validation:
    name: input validation
    runs-on: [ubuntu-latest]
    steps:
      - name: Validate input
        run: |
          if [ -z "${{ inputs.version_tag }}" ]; then
            echo "Missing version_tag input"
            exit 1
          fi

  build:
    needs: input_validation
    uses: ./.github/workflows/build.yml
    secrets: inherit
    
  release:
    name: Release
    needs: build
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set transformed release version name
        run: echo "RELEASE_VERSION_DASHED=`echo ${{ inputs.version_tag }} | sed 's/\./-/g'`" >> $GITHUB_ENV

      - name: echo transformed release version name
        run: echo $RELEASE_VERSION_DASHED
