name: Release and Docker build and push to production JFrog

on:
  workflow_call:
    inputs:
      version_tag:
        description: "tag of the release"
        required: false
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  release:
    name: release version
    runs-on: [self-hosted, Linux, standard]
    steps:
      - name: Create release version
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ env.GITHUB_TOKEN }}"
          title: "${{ github.event.inputs.version_tag }}"
          prerelease: false
          files: |
            *.md
