name: release


permissions:
  id-token: write
  contents: write
  actions: write
  pull-requests: write

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_call:
    inputs:
      version_tag:
        description: "tag of the release"
        required: false
        type: string

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set release major version variable from pushed tag
        run: echo "RELEASE_VERSION=`echo ${GITHUB_REF##*/} | cut -c 1-2`" >> $GITHUB_ENV
        if: "${{ inputs.version_tag == '' }}"
      
      - name: Set release major version variable from workflow input
        run: echo "RELEASE_VERSION=`echo ${{ inputs.version_tag }}`" >> $GITHUB_ENV
        if: "${{ inputs.version_tag != '' }}"

      
      - name: echo RELEASE_VERSION
        run: echo $RELEASE_VERSION
